name: Despliegue atomatizado
on: push
jobs:
  despliegue:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
      node-version: '14'
    - run: npm run deploy